### ISSUE TITLE
Swagger Online Validator results

### ISSUE THREAD

**Issue by mark05e** [mark05e/NiceIncontactAPI-Admin#1]
Online validator at https://apitools.dev/swagger-parser/online/ using url as https://raw.githubusercontent.com/mark05e/NiceIncontactAPI-Admin/main/admin-api-docs shows below response:

```
Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
    Data does not match any schemas from 'oneOf' at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
      Missing required property: schema at #/
      Data does not match any schemas from 'oneOf' at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
    Missing required property: $ref at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
 
JSON_OBJECT_VALIDATION_FAILED

Error: Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
    Data does not match any schemas from 'oneOf' at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
      Missing required property: schema at #/
      Data does not match any schemas from 'oneOf' at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
    Missing required property: $ref at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
 
JSON_OBJECT_VALIDATION_FAILED
    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79834)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231669

SyntaxError: Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
    Data does not match any schemas from 'oneOf' at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
      Missing required property: schema at #/
      Data does not match any schemas from 'oneOf' at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
        Additional properties not allowed: allowMultiple at #/
    Missing required property: $ref at #/paths//suppressed-contact/{suppressedContactId}/delete/parameters/0
 
JSON_OBJECT_VALIDATION_FAILED
    at Function.o [as syntax] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79834)
    at validateSchema (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:4986)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3136)

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at ZSchema.getLastError (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:215273)
    at validateSchema (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:4890)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3136)
```

**Comment by mark05e** [comment]
Might be https://github.com/mark05e/NiceIncontactAPI-Admin/blob/6d5b377a1bbbc944d069f0952090b7a60b84555c/Admin/General#L502-L527

**Comment by mark05e** [comment]
When running against https://validator.swagger.io/, does not show any error
